import TextInput from '@/components/form/TextInput/index.vue';
import TextArea from '@/components/form/TextArea/index.vue';
import Select from '@/components/form/Select/index.vue';
import DatePicker from '@/components/form/DatePicker/index.vue';
import Button from '@/components/reusable/Button/index.vue';
import Alert from '@/components/reusable/Alert/index.vue';
import Toast from '@/components/reusable/Toast/index.vue';
import Card from '@/components/reusable/Card/index.vue';
import List from '@/components/reusable/List/index.vue';
import Pagination from '@/components/reusable/Pagination/index.vue';
import Dropdown from '@/components/reusable/Dropdown/index.vue';
import Modal from '@/components/reusable/Modal/index.vue';
import Breadcrumb from '@/components/reusable/Breadcrumb/index.vue';
import Table from '@/components/reusable/Table/index.vue';

export const component = (app) => {
  app.component('TextInput', TextInput);
  app.component('TextArea', TextArea);
  app.component('Select', Select);
  app.component('DatePicker', DatePicker);
  app.component('Button', Button);
  app.component('Alert', Alert);
  app.component('Toast', Toast);
  app.component('Card', Card);
  app.component('List', List);
  app.component('Pagination', Pagination);
  app.component('Dropdown', Dropdown);
  app.component('Modal', Modal);
  app.component('Breadcrumb', Breadcrumb);
  app.component('Table', Table);
  return app;
};
